config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'admin/sessions#new'
   get '/logout' => 'admin/sessions#destroy'

  namespace :admin do
  resources :comments, only: [:index, :update, :destroy]
  resources :tags, except: [:index]
  resources :posts	
  resources :sessions, only: [:new, :create, :destroy]
  resources :moderators, only: [:index, :edit, :update]
end
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :visitor
  has_many :notifications, as: :notifiable, dependent: :destroy

  def self.matching_fullname_or_message params
	joins(:visitor).where("fullname LIKE ? OR message LIKE ?", "%#{params}%", "%#{params}%")
	end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :visitor
end

app/models/moderator.rb
class Moderator < ApplicationRecord
	has_secure_password
	has_many :posts

	validates :fullname, presence: true
	validates :username, presence: true, format: {with: /@/, message: 'is not valid'}
	validates :password, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many  :tags, through: :post_tags
  belongs_to :moderator
  
  validates :title, presence: true
  validates :content, presence: true
  


def self.matching_title_or_content search
  	where("title LIKE ? OR content LIKE ?","%#{search}%","%#{search}%")
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :posts, through: :post_tags

	validates :name, presence: true

	def in_use?
		PostTag.exists?(tag_id: self.id)
	end
end

app/models/visitor.rb
class Visitor < ApplicationRecord
	has_many :notifications, as: :notifiable
	has_many :comments
	has_many :messages

end
 

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  def index
    if params[:search].present?
      @comments = Comment.matching_fullname_or_message(params[:search]).page params[:page]
  	else
    @comments = Comment.where(status: to_bool(params[:status])).page params[:page]
  end
 end
  def update
  	@comment = Comment.find(params[:id])
  	if @Comment.update(status: params[:status])
  	redirect_to :back, notice: 'successfully updated Comment'
  else
  	redirect_to :back, notice: 'There was a problem updating comment'
  	end
  end
 
  def destroy
  	@comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to :back, notice: 'comment was successfully deleted'
  end
  end

app/controllers/admin/moderators_controller.rb
 class Admin::ModeratorsController < Admin::ApplicationController
 	def index
 		@moderators = Moderator.all
 		
 	end

 	def edit
 		@moderator = Moderator.find(params[:id]) 		
 	end

 	def update
 		@moderator = Moderator.find(params[:id])
 		if @moderator.update(moderator_params)
 			flash[:notice] = "Moderator was successfuly updated"
 			redirect_to  admin_moderators_url
 		else
 			flash[:alert] = "Problem updating moderator"
 			render 'edit'
 		end 		
 	end

 	private

 	def moderator_params
 		params.require(:moderator).permit(:id, :fullname, :username, :password)
 		
 	end
 end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
   def index

     if params[:search].present?
    @posts = Post.matching_title_or_content(params[:search]).page params[:page]
    else
    @posts = Post.all.order(id: :desc).page params[:page]
  end
  end

  def new
    @post = Post.new
  end

  def create
     @post = Post.new(post_params)
    @post.moderator_id = current_moderator.id
    if @post.save
      redirect_to admin_posts_url, notice: 'post was successfully created'
    else
      flash[:alert] = 'There was a problem creating  a post'
      render :new
      
    end
  end

  def edit
  @post = Post.find(params[:id])  
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_posts_url, notice: 'Post was successfully Updated!!'
    else
      flash[:alert] = 'There was a problem updating the post'
      render :edit
      
    end
  end

  def show
     @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to :back, notice: 'Post was successfully deleted'
  end

  private

  def post_params
    params.require(:post).permit(:id, :title, :content, :publish, tag_ids: [])
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::ApplicationController
  before_action :authorize, except: [:new, :create]

  def new
  end

  def create
  	@moderator = Moderator.find_by(username: params[:username]).try(:authenticate, params[:password])
    if @moderator
    session[:current_moderator_id] = @moderator.id
    redirect_to admin_moderators_url, notice: 'You have successfuly signed in'
else
	flash[:alert] = 'There was a problem with your username or password'
	render :new 
end
  end

  def destroy
    session[:current_moderator_id] = nil
    redirect_to 'login', notice: 'You have successfuly logged out'
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::ApplicationController
  def new
    @tag = Tag.new
    @tags = Tag.all.order(id: :desc)
  end

  def create
    tags_params[:name].split(',').map do |n|
      Tag.new(name:n).save
    end
    redirect_to new_admin_tag_url, notice: 'Tag was successfully created'
  end

  def edit
    @tag =Tag.find(params[:id])
  end

  def update
     @tag =Tag.find(params[:id])
     if @tag.update tags_params
      redirect_to new_admin_tag_url, notice: 'successfully updated tag'
    else
      flash[:alert] = 'Thare was a problem updating tag'
      render :edit
       
     end
  end

  def show
  end

  def destroy
    @tag =Tag.find(params[:id])
    @tag.destroy
    redirect_to :back, notice: 'successfully deleted tag '
  end
  private
  def tags_params
    params.require(:tag).permit(:id, :name)
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
	def create_deletable_button tag
		 if tag.in_use? 

		 link_to '#' do 
		 	content_tag(:button, 'Delete', class: 'disabled')
		 end
		else
		 
		 link_to admin_tag_path(tag), method: :delete do 
		
		content_tag(:button, 'Delete')
		 end 
		 end 
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def status_converter(status, truthy: 'Active', falsey: 'Pending')
		if status
			truthy
		else
			falsey
		end
	end

	def time_ago time
		"#{time_ago_in_words(time)}  ago"
		
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/comments/index.html.erb
<h1>Comments</h1>
<p> 
<%= render 'search', route: admin_comments_path %>

 </p>


<p><%= link_to 'Approved', admin_comments_path(status: true) %>
<%= link_to 'Un-approved', admin_comments_path(status: false) %>
</p>

<% @comments.each do |comment| %>
<p><b><%= comment.visitor.fullname %></b>posted message on<b><%= comment.post.title %></b> </p>
<p><%= comment.message %></p>
<p><%= link_to 'Delete', admin_comments_path(coment), method: :delete, data: {confirm: 'Are you sure?'} %></p>
<p>
<%= 
if params[:status] == 'true'
link_to 'Un-approve', admin_comments_path(comment, status: false), method: :put
else
	link_to 'Approve', admin_comments_path(comment, status: true), method: :put 
end
%>
</p>
<hr>
<% end %>
<%= paginate @comments %>

app/views/admin/posts/_form.html.erb
<p><%= render 'validation_errors', object: @post %></p>

<%= form_for [:admin, @post] do |f| %>
   <p>
   	<%= f.label :title %><br>
   	<%= f.text_field :title %>
   </p>

   <p>
   	<%= f.label :content %><br>
   	<%= f.text_field :content %>
   </p>

   <p>
   	<%= f.label :publish %><br>
   	<%= f.check_box :publish %>
   </p>
   <p>
   	<%= f.select :tag_ids, Tag.all.collect {|t| [t.name, t.id]}, {prompt: 'Select Tag'}, multiple: :true %>
   </p>
   <p><%= f.submit %></p>

<% end %>

app/views/admin/posts/edit.html.erb
<h1>Admin::Posts#edit</h1>
<p>Find me in app/views/admin/posts/edit.html.erb</p>
<%= render 'form' %> 

app/views/admin/posts/index.html.erb
<h1>Admin::All Posts</h1>

<p><%= link_to 'New Post', new_admin_post_path %></p>

<p>
   <%= form_tag(admin_posts_path, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag 'Search' %>
  <% end %>
 </p>

<table class="table table-bordered table-hover">
   <thead>
   <tr>
	<th>title   </th>
	<th>publish</th>
	<th>actions</th>
	
	</tr>
	</thead>
	<tbody>
	
		<% @posts.each do |post| %>
		<tr>
			<td><%= truncate(post.title, length:65, separate: '') %></td> 
			<td><%=  status_converter(post.publish, truthy: 'Active', falsey: 'Pending') %></td>
			<td>
			<%= link_to 'Edit', edit_admin_post_path(post) %> |
			<%= link_to 'Show', admin_post_path(post) %> |
			<%= link_to 'Delete', admin_post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %>
			</td>
			
		</tr>
		<% end %>
		
	</tbody>
</table> 
<p><%= paginate @posts %></p>

app/views/admin/posts/new.html.erb
<h1>Admin::Posts#new</h1>

<%= render 'form' %> 

app/views/admin/posts/show.html.erb
<h1>Admin::Show Post</h1>
<p><b>title:</b> <%= @post.title %></p>
<p><b>content:</b> <%= @post.content %></p>
<p><b>publish:</b> <%= status_converter(@post.publish) %></p>
<p><b>created:</b> <%= time_ago (@post.created_at) %></p>

app/views/admin/tags/edit.html.erb
<h1>Admin::Edit Tags</h1>
<%= form_for [:admin, @tag] do |f| %>
<p><%= f.label :name %></p>
<p><%= f.text_field :name%></p>
<p><%= f.submit %></p>
<% end %>

app/views/admin/tags/new.html.erb
<h1>Admin::New Tags</h1>
<%= form_for [:admin, @tag] do |f| %>
<p> <%= f.text_area :name, placeholder: 'e.g Ruby, Python, php' %></p>
<p><%= f.submit %></p>
<% end %>

<table class="table table-bordered table-hover">
   <thead>
   <tr>
	<th>name</th>
	<th>status</th>
	<th>created</th>
	<th>actions</th>
	</tr>
	</thead>
	<tbody>
		<% @tags.each do |tag| %>
		<tr>
			<td><%= tag.name %></td>
			<td><%= status_converter(tag.in_use?, truthy: 'in use', falsey: 'not in use') %></td>
			<td><%= time_ago tag.created_at %></td>
			<td>
				<%= link_to edit_admin_tag_path(tag) do %>
				<button type="button">Edit</button>
				<% end %>
				<%= create_deletable_button tag %>

				
			</td>
		</tr>

		<% end %>
	</tbody>
</table> 

app/views/admin/tags/show.html.erb
<h1>Admin::Tags#show</h1>
<p>Find me in app/views/admin/tags/show.html.erb</p>