config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'admin/sessions#new'
   get '/logout' => 'admin/sessions#destroy'

  namespace :admin do
  resources :comments, only: [:index, :update, :destroy]
  resources :tags, except: [:index]
  resources :posts	
  resources :sessions, only: [:new, :create, :destroy]
  resources :moderators, only: [:index, :edit, :update]
end
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :visitor
  has_many :notifications, as: :notifiable, dependent: :destroy

  def self.matching_fullname_or_message params
	joins(:visitor).where("fullname LIKE ? OR message LIKE ?", "%#{params}%", "%#{params}%")
	end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :visitor
end

app/models/moderator.rb
class Moderator < ApplicationRecord
	has_secure_password
	has_many :posts

	validates :fullname, presence: true
	validates :username, presence: true, format: {with: /@/, message: 'is not valid'}
	validates :password, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many  :tags, through: :post_tags
  belongs_to :moderator
  
  validates :title, presence: true
  validates :content, presence: true
  


def self.matching_title_or_content search
  	where("title LIKE ? OR content LIKE ?","%#{search}%","%#{search}%")
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :posts, through: :post_tags

	validates :name, presence: true

	def in_use?
		PostTag.exists?(tag_id: self.id)
	end
end

app/models/visitor.rb
class Visitor < ApplicationRecord
	has_many :notifications, as: :notifiable
	has_many :comments
	has_many :messages

end
 

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
   def index

     if params[:search].present?
    @posts = Post.matching_title_or_content(params[:search]).page params[:page]
    else
    @posts = Post.all.order(id: :desc).page params[:page]
  end
  end

  def new
    @post = Post.new
  end

  def create
     @post = Post.new(post_params)
    @post.moderator_id = current_moderator.id
    if @post.save
      redirect_to admin_posts_url, notice: 'post was successfully created'
    else
      flash[:alert] = 'There was a problem creating  a post'
      render :new
      
    end
  end

  def edit
  @post = Post.find(params[:id])  
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_posts_url, notice: 'Post was successfully Updated!!'
    else
      flash[:alert] = 'There was a problem updating the post'
      render :edit
      
    end
  end

  def show
     @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to :back, notice: 'Post was successfully deleted'
  end

  private

  def post_params
    params.require(:post).permit(:id, :title, :content, :publish, tag_ids: [])
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::ApplicationController
  def new
    @tag = Tag.new
    @tags = Tag.all.order(id: :desc)
  end

  def create
    tags_params[:name].split(',').map do |n|
      Tag.new(name:n).save
    end
    redirect_to new_admin_tag_url, notice: 'Tag was successfully created'
  end

  def edit
    @tag =Tag.find(params[:id])
  end

  def update
     @tag =Tag.find(params[:id])
     if @tag.update tags_params
      redirect_to new_admin_tag_url, notice: 'successfully updated tag'
    else
      flash[:alert] = 'Thare was a problem updating tag'
      render :edit
       
     end
  end

  def show
  end

  def destroy
    @tag =Tag.find(params[:id])
    @tag.destroy
    redirect_to :back, notice: 'successfully deleted tag '
  end
  private
  def tags_params
    params.require(:tag).permit(:id, :name)
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
	def create_deletable_button tag
		 if tag.in_use? 

		 link_to '#' do 
		 	content_tag(:button, 'Delete', class: 'disabled')
		 end
		else
		 
		 link_to admin_tag_path(tag), method: :delete do 
		
		content_tag(:button, 'Delete')
		 end 
		 end 
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def status_converter(status, truthy: 'Active', falsey: 'Pending')
		if status
			truthy
		else
			falsey
		end
	end

	def time_ago time
		"#{time_ago_in_words(time)}  ago"
		
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		  <% if flash[:notice] %>
		  <div class="notice"> <%= flash[:notice] %></div>
		  <% end %>

		  <% if flash[:alert] %>
		  <div class="alert"><%= flash[:alert] %></div>
		  <% end %>
      <%= link_to 'Log out', logout_path %>
      <p>
       <%= link_to 'Posts', admin_posts_path %>
        <%= link_to 'Moderators', admin_moderators_path %>
        <%= link_to 'Tags', new_admin_tag_path %>
        <%= link_to 'Comments', admin_comments_path %>
        </p>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		  <% if flash[:notice] %>
		  <div class="notice"> <%= flash[:notice] %></div>
		  <% end %>

		  <% if flash[:alert] %>
		  <div class="alert"><%= flash[:alert] %></div>
		  <% end %>
      <%= link_to 'Log out', logout_path %>
    <%= yield %>
  </body>
</html>